package com.outr.stripe.charge

case class Card(id: String,
               `object`: String,
                addressCity: Option[String],
                addressCountry: Option[String],
                addressLine1: Option[String],
                addressLine1Check: Option[String],
                addressLine2: Option[String],
                addressState: Option[String],
                addressZip: Option[String],
                addressZipCheck: Option[String],
                brand: String,
                country: String,
                customer: Option[String],
                cvcCheck: Option[String],
                dynamicLast4: Option[String],
                expMonth: Int,
                expYear: Int,
                funding: String,
                last4: String,
                metadata: Map[String, String],
                name: Option[String],
                tokenizationMethod: Option[String])
