package com.outr.stripe.charge

case class Card(id: String,
               `object`: String,
                account: Option[String],
                addressCity: Option[String],
                addressCountry: Option[String],
                addressLine1: Option[String],
                addressLine1Check: Option[String],
                addressLine2: Option[String],
                addressState: Option[String],
                addressZip: Option[String],
                addressZipCheck: Option[String],
                brand: String,
                country: Option[String],
                currency: Option[String],
                customer: Option[String],
                cvcCheck: Option[String],
                defaultForCurrency: Option[String],
                dynamicLast4: Option[String],
                number: Option[String],
                expMonth: Int,
                expYear: Int,
                fingerprint: Option[String],
                cvc: Option[Int],
                funding: String,
                last4: String,
                metadata: Map[String, String],
                name: Option[String],
                recipient: Option[String],
                threeDSecure: Option[String],
                tokenizationMethod: Option[String])

object Card {
  def create(number: String,
             expMonth: Int,
             expYear: Int,
             cvc: Option[Int] = None,
             name: Option[String] = None,
             addressCity: Option[String] = None,
             addressCountry: Option[String] = None,
             addressLine1: Option[String] = None,
             addressLine2: Option[String] = None,
             addressState: Option[String] = None,
             addressZip: Option[String] = None,
             currency: Option[String] = None): Card = {
    Card(
      id = null,
      `object` = "card",
      account = None,
      addressCity = addressCity,
      addressCountry = addressCountry,
      addressLine1 = addressLine1,
      addressLine1Check = None,
      addressLine2 = addressLine2,
      addressState = addressState,
      addressZip = addressZip,
      addressZipCheck = None,
      brand = "",
      country = None,
      currency = None,
      customer = None,
      cvcCheck = None,
      defaultForCurrency = None,
      dynamicLast4 = None,
      number = Some(number),
      expMonth = expMonth,
      expYear = expYear,
      fingerprint = None,
      cvc = cvc,
      funding = "",
      last4 = "",
      metadata = Map.empty,
      name = name,
      recipient = None,
      threeDSecure = None,
      tokenizationMethod = None
    )
  }
}
